version: '2'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Max12345!"
    ports:
      - 11433:1433

  rabbit:
    image: "rabbitmq:3.8.2-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"