name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: dotnet tool restore
      run: dotnet tool restore
    - name: set GitVersion
      run: dotnet dotnet-gitversion /output buildserver /nofetch
    - name: dotnet pack
      run: dotnet pack --output $(Build.ArtifactStagingDirectory) --include-symbols /p:Configuration=$(BuildConfiguration) --verbosity Normal /p:Version=$(GitVersion.NuGetVersion)
