name: publish-nuget-packages

on: 
  release:
    types: [published, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'
    - run: dotnet pack prometheus-net.Contrib.sln --include-symbols -c "Release" --output "build/"
    - run: dotnet nuget push "build/*.symbols.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s "https://api.nuget.org/v3/index.json" -n true
